BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Pessoa] (
    [idPessoa] INT NOT NULL IDENTITY(1,1),
    [nome] NVARCHAR(1000) NOT NULL,
    [cpf] NVARCHAR(1000) NOT NULL,
    [dataNascimento] DATETIME2 NOT NULL,
    CONSTRAINT [Pessoa_pkey] PRIMARY KEY CLUSTERED ([idPessoa]),
    CONSTRAINT [Pessoa_cpf_key] UNIQUE NONCLUSTERED ([cpf])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
